#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1) uniform sampler2D depthBuffer;
layout(set = 0, binding = 2, rgba16f) uniform image2D storageImage;

struct RayPayload {
    vec3 hitColor;
    float distance;
    uint materialIndex;
};

layout(set = 1, binding = 0) uniform LightUBO {
    vec4 position;
    vec4 color;
} lightData;

struct Material {
    vec4 color;
};

layout(std430, set = 0, binding = 3) buffer Materials {
    Material materialData[];
} materials;

layout(set = 1, binding = 1) uniform InverseViewProj {
    mat4 invViewMatrix;
    mat4 invProjMatrix;
} inverseViewProj;

layout(location = 0) rayPayloadEXT RayPayload rayPayload;


void main() {
    uint rayFlags = gl_RayFlagsOpaqueEXT;

    float tMin = 0.1;
    float tMax = 1000.0f;

    const ivec2 pixelCoords = ivec2(gl_LaunchIDEXT.xy);
    float depth = texelFetch(depthBuffer, pixelCoords, 0).r;
    vec2 uv = vec2(gl_LaunchIDEXT.xy + 0.5) / vec2(gl_LaunchSizeEXT.xy);
    vec4 ndcPos = vec4(uv * 2.0 - 1.0, depth, 1.0);
    vec4 origin = inverseViewProj.invViewMatrix * (inverseViewProj.invProjMatrix * ndcPos);
    origin /= origin.w;


    traceRayEXT(
        topLevelAS,
        rayFlags,
        0xFF,
        0,
        0,
        0,
        origin.xyz,
        tMin,
        normalize(lightData.position - origin).xyz,
        tMax,
        0
    );

    //imageStore(storageImage, pixelCoords, vec4(rayPayload.hitColor, 1.0));
    if (rayPayload.distance < 0) {
        imageStore(storageImage, pixelCoords, vec4(1));
        return;
    }
    imageStore(storageImage, pixelCoords, materials.materialData[rayPayload.materialIndex].color);


}